title: "Hacker Hangar"
description: "My cybersecurity journey, documented."
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
paginate: 10
plugins:
- jekyll-remote-theme
- jekyll-include-cache
baseurl: "/hacker-hangar"
url: "https://rohan-shan-tze.github.io"
